# Generated by Django 4.1.4 on 2022-12-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
